### ISSUE TITLE
airtable problems

### ISSUE THREAD

**Issue by deathpact** [leroychan/twilio-frontline-quick-deploy-v2#1]

**Comment by KeithKolo** [comment]
If I wanted frontline to handle incoming text messages and yet also keep a log of those messages in this airtable base how would this code change? I was able to build a text message log function in the twilio serverless function that I am using for this quick deploy but I cannot for the life of me figure out how to have twilio call that function. I either am able to have frontline handle the messages or the twilio function that I built to log the text in airtable?
